spring.application.name=email-writer-assistant

server.port=8081

ai.provider=groq

groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.model=llama-3.3-70b-versatile
groq.api.key=${GROQ_API_KEY:}




gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent?key=

gemini.api.key=${GEMINI_API_KEY:}
